### ISSUE TITLE
Home not displaying anything

### ISSUE THREAD

**Issue by dilonne** [burhanrashid52/YoutubeUX#1]
Hi, I cloned the repo and ran the project but the home is  only showing white, could you kindly assist on how to make it load content

**Comment by burhanrashid52** [comment]
Is there any error logging in stacktrace?

**Comment by dilonne** [comment]
No its just showing a white blank screen

**Comment by dilonne** [comment]
Its now working!!, thanks.

**Comment by dilonne** [comment]
Can I download a video for offline watching?

**Comment by burhanrashid52** [comment]
No, Its just showcase Youtube UI/UX

**Comment by dilonne** [comment]
Okay I was wondering because according to the architecture, data is either coming from the local SQLite db or from a webservice

**Comment by burhanrashid52** [comment]
Yes, its just to demonstrate the usage of Android Architecture components.

**Comment by dilonne** [comment]
Thanks
