### ISSUE TITLE
Can we use the same logic to build something similar to facebook comment screen

### ISSUE THREAD

**Issue by raghunandankavi2010** [burhanrashid52/YoutubeUX#4]
In fb the comment screen has a recyclerview and you hold and drag the dialog it scales down.
Looking for a way to achieve the same.
This is just a question and nothing do with the repo.

**Comment by raghunandankavi2010** [comment]
Thank you. Since this is not related to the repo its better to close down. I think i found something similar to what i want on another repo!.

**Comment by burhanrashid52** [comment]
Can you share the link? It might help other devs here.

**Comment by raghunandankavi2010** [comment]
@burhanrashid52  https://github.com/woxingxiao/BounceScrollView.
Using a nested scrollview with recyclerview although we still need to take care when user scrolls recyclerview. I am also interested in a alternate solution if anyone is able to achieve the same. Your repo was helpful. Thank you!.

**Comment by raghunandankavi2010** [comment]
@burhanrashid52 in bouncescrollview i added the below code. If the touch and move is greater than 50% in both directions you animate the scrollview to move it off screen. This is just a gist i came up with. Also if you use nest recyclerview we need to take into account whether rv is scrolling or not. 

           MotionEvent.ACTION_UP, MotionEvent.ACTION_CANCEL -> {
                mPreDelta = 0
                //mOverScrolledDistance = 0;
                val half = (Resources.getSystem().displayMetrics.heightPixels.toFloat()/2)
                val scrolledDistance = mOverScrolledDistance
                percentVertical = (ev.rawY + dY) / deviceHeight.toFloat()
                Log.i("Scrolled Distance", "$scrolledDistance")
                when (getDirection(startX = startX, startY = startY, endX = ev.rawX, endY = ev.rawY)) {
                    is Direction.UP -> {

                        mAnimator = if (scrolledDistance > half) {
                            Log.i("Scrolled Distance up", "$mOverScrolledDistance nd half of device height $half")
                            ObjectAnimator.ofFloat(mChildView, View.TRANSLATION_Y, - Resources.getSystem().displayMetrics.heightPixels.toFloat())
                        } else {
                            ObjectAnimator.ofFloat(mChildView, View.TRANSLATION_Y, 0f)
                        }
                    }
                    is Direction.DOWN ->{
                        mAnimator = if (Math.abs(scrolledDistance) > half) {
                            Log.i("Scrolled Distance up", "$mOverScrolledDistance and half of device height $half")
                            ObjectAnimator.ofFloat(mChildView, View.TRANSLATION_Y, Resources.getSystem().displayMetrics.heightPixels.toFloat())
                        } else {
                            ObjectAnimator.ofFloat(mChildView, View.TRANSLATION_Y, 0f)
                        }
                    }
                }

                cancelAnimator()
                if (isScrollHorizontally) {
                    mAnimator = ObjectAnimator.ofFloat(mChildView, View.TRANSLATION_X, 0f)
                } else { // mAnimator = ObjectAnimator.ofFloat(mChildView, View.TRANSLATION_Y, 0);
                }
                mAnimator.setDuration(mBounceDelay).interpolator = mInterpolator
                if (mOverScrollListener != null) {
                    mAnimator.addUpdateListener(AnimatorUpdateListener { animation ->
                        val value = animation.animatedValue as Float
                        mOverScrollListener!!.onOverScrolling(value <= 0, Math.abs(value.toInt()))
                    })
                }
                mAnimator.addListener(object: Animator.AnimatorListener{
                    override fun onAnimationRepeat(animation: Animator?) {
                    }

                    override fun onAnimationEnd(animation: Animator?) {
                       mOverScrolledDistance = 0
                    }

                    override fun onAnimationCancel(animation: Animator?) {

                    }

                    override fun onAnimationStart(animation: Animator?) {

                    }

                })
                mAnimator.start()
            }
